### ISSUE TITLE
Add JavaScript to automatically update for desktop wallet installation links

### ISSUE THREAD

**Issue by markmhx** [blockstack/hiro.so#11]
We should add a JavaScript snippet to the desktop wallet install page in Webflow that automatically pulls the latest build URLs for the extension types (1 MacOS, 1 Windows and 2 Linux) and sets the relevant `href` values with them in the page.

Currently we have to manually update these links by hand each time we cut a new production release, which a chore susceptible to delays and errors.

I've had this in my personal todo list for a few weeks now, so it's best I move this into GitHub in case someone can pick it up faster than me.

You can see my code for preparing this before insertion into Webflow [here](https://codepen.io/markmhendrickson/pen/JjRgbwG).

**Comment by markmhx** [comment]
@kyranjamie Can you complete the code as presented in the Codepen preview above so that it works for assigning the latest `href` to the three `a` tags indicated by their IDs as shown? I'll then load into Webflow.

**Comment by kyranjamie** [comment]
```html
<a class="download-link" data-asset-ext="dmg" href="#">dmg</a>
<a class="download-link" data-asset-ext="exe" href="#">exe</a>
<a class="download-link" data-asset-ext="rpm" href="#">rpm</a>
<a class="download-link" data-asset-ext="deb" href="#">deb</a>
```

```js
$(document).ready(() => {
  const links = $('.download-link');
  console.log(links);
  
  fetch('https://api.github.com/repos/blockstack/stacks-wallet/releases').then(resp => resp.json()).then(releases => {
    return releases
      .filter(release => release.tag_name.startsWith('v4'))
      .filter(release => !release.tag_name.includes('beta'))
  })
  .then(releases => {
    const release = releases[0];
    const assets = release.assets.filter(a => a.name.includes('mainnet'));

    links.each((i, el) => {
      const ext = el.getAttribute('data-asset-ext');
      const assetUrl = assets.find(a => a.name.endsWith(ext)).browser_download_url;
      el.setAttribute('href', assetUrl)
    })
  });
});
```

**Comment by markmhx** [comment]
Published to Webflow 🚀
