### ISSUE TITLE
Add wallet FAQ about usernames / IDs and renewals

### ISSUE THREAD

**Issue by markmhx** [blockstack/hiro.so#2]
We should have a general FAQ about usernames including information such as the following:

- Usernames can be used in the new web wallet for testing only at the moment, with link
- Usernames can also be used with the older app.blockstack.org and Blockstack Browser, but only until they sunset on July 1, 2021
- Usernames were automatically renewed upon release of Stacks 2.0 (@hstove I believe you mentioned this is the case? Until when?)
- Options for renewing names in the future (e.g. via web wallet with transaction signing, either app-based or within its UI. Or perhaps CLI)

**Comment by hstove** [comment]
Some follow-up:
- Usernames from Stacks 1.0 will show up in the web wallet, but any usernames registered on stacks 2.0 are not yet visible
- All IDs were automatically renewed at the launch of Stacks 2.0 for two years

**Comment by GinaAbrams** [comment]
@markmhx what FAQ should this go on? Or should it be the status page?

**Comment by markmhx** [comment]
I think we'll need to create a new FAQ for this.

**Comment by GinaAbrams** [comment]
> I think we'll need to create a new FAQ for this.

As in a new page entirely, or a question listed out on the web wallet page or elsewhere?

**Comment by markmhx** [comment]
A new question item in the CMS that's displayed on the wallet page.

**Comment by GinaAbrams** [comment]
copy that!
