### ISSUE TITLE
Update FAQ for BTC withdrawal with unsupported hardware device guidance

### ISSUE THREAD

**Issue by markmhx** [blockstack/hiro.so#6]
We should add instructions to [the BTC withdrawal FAQ](https://www.hiro.so/questions/how-can-i-withdraw-the-btc-ive-deposited-into-the-stacks-wallet-v3-x) for desktop wallet users who are unable to authenticate with their Ledger or Trezor devices.

These instructions should explain how to migrate STX holdings over to another seed phrase as saved on a newly configured Ledger or Trezor device so the user can then safely enter the original seed phrase directly into the Stacks Wallet (software mode) to retrieve their BTC.

It should note that users need to migrate all other crypto holdings associated with the original phrase as well. And that any user still awaiting STX to unlock may need to wait until as late as September 2021 when all STX will be unlocked on Stacks 2.0.

**Comment by GinaAbrams** [comment]
@markmhx mind adding some proposed text to answer this in the [wip paper doc here for edits](https://paper.dropbox.com/doc/FAQs-to-add-to-Hiro.sowallet--BGxYWJ1vv1hXb9NzTOqW8xHwAg-aSoX9Q2GYGvBO3FTU7y56)? 🙏

**Comment by markmhx** [comment]
This FAQ is now updated: https://www.hiro.so/questions/how-can-i-withdraw-the-btc-ive-deposited-into-the-stacks-wallet
